# Stage 2: Feature Engineering

Since in the first stage I've already done some feature selection and feature engineering, now I'm just going to prepare the data to be able to be used by the ML algorithms. The goal is to transform any categorical data into a more suitable form. In ordert o accomplish that task I'll use OneHotEncoding transforming categories into vectors with binary data.

In [1]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('./cleaned_dataset.csv')

#### I'm going to drop lat and long features as those are highly correlated to neighborhoods. I'll keep just neighborhood. Same thing with ars_m2 and ars_price. No need to keep them both.

In [7]:
df.drop(['lat','lon'], axis=1, inplace=True)

In [8]:
df.head()

  neighborhood  rooms  bedrooms  bathrooms  surface_covered  ars_price  ars_m2
0    Mataderos      1         0          2               35    5200000  148571
1     Saavedra      1         0          1               22    2695500  122522
2     Saavedra      1         0          1               22    2380500  108204
3         Boca      1         0          1               31    3445000  111129
4         Boca      4         3          1               78    8450000  108333

#### Then I'll transform the categorical feature into a vector.

In [9]:
df = pd.get_dummies(df, columns=['neighborhood'])

In [10]:
df

,rooms,bedrooms,bathrooms,surface_covered,ars_price,ars_m2,neighborhood_Abasto,neighborhood_Agronomía,neighborhood_Almagro,neighborhood_Balvanera,...,neighborhood_Villa Lugano,neighborhood_Villa Luro,neighborhood_Villa Ortuzar,neighborhood_Villa Pueyrredón,neighborhood_Villa Real,neighborhood_Villa Riachuelo,neighborhood_Villa Santa Rita,neighborhood_Villa Soldati,neighborhood_Villa Urquiza,neighborhood_Villa del Parque
0,1,0,2,35,5200000,148571,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,1,22,2695500,122522,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,1,22,2380500,108204,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,1,31,3445000,111129,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,3,1,78,8450000,108333,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,2,1,1,51,9815000,192450,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,2,1,1,54,10075000,186574,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,3,2,1,41,6435000,156951,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,2,1,1,41,8255000,201341,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,3,2,1,56,9555000,170625,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,3,2,1,42,9750000,232142,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,2,1,1,42,9750000,232142,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,1,0,1,27,4875000,180555,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,1,0,1,28,4875000,174107,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
14,1,0,2,33,6415500,194409,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
15,3,2,1,57,9750000,171052,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
16,3,2,1,93,14430000,155161,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
17,4,3,2,93,14885000,160053,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
18,2,1,1,32,6175000,192968,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
19,4,3,2,78,16835000,215833,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
20,1,0,1,39,9555000,245000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,1,0,2,52,14235000,273750,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,2,1,1,60,21970000,366166,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,4,3,2,65,14950000,230000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,1,0,1,32,8970000,280312,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,1,0,1,33,10075000,305303,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,1,0,1,38,13000000,342105,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,2,1,1,44,11050000,251136,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,3,2,1,80,14235000,177937,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,2,1,2,45,14170000,314888,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36222,4,3,3,95,23725000,249736,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36223,4,3,2,263,84500000,321292,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36224,4,3,3,110,14950000,135909,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
36225,4,3,2,75,15210000,202800,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36226,4,3,2,71,14950000,210563,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36227,4,3,2,82,19175000,233841,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36228,4,3,2,85,18655000,219470,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36229,4,3,3,121,20800000,171900,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36230,4,3,2,71,12935000,182183,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36231,4,3,2,133,33150000,249248,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36232,4,3,1,102,20020000,196274,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36233,4,3,2,130,29250000,225000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36234,4,3,1,97,19175000,197680,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36235,4,3,3,98,19500000,198979,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36236,4,3,2,70,12675000,181071,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36237,4,3,1,64,9945000,155390,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36238,4,3,3,72,9945000,138125,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36239,4,3,2,132,20150000,152651,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36240,4,2,1,81,6012500,74228,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
36241,4,3,2,95,15925000,167631,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36242,5,4,3,138,20800000,150724,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36243,5,4,2,217,55900000,257603,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36244,5,4,3,138,20800000,150724,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36245,5,2,2,150,18525000,123500,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36246,6,5,3,158,27300000,172784,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36247,6,3,3,226,78000000,345132,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36248,6,4,3,143,29900000,209090,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36249,6,3,2,72,13650000,189583,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36250,7,5,2,212,38870000,183349,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36251,7,6,5,487,26975000,55390,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
df.to_csv('./final_dataset.csv', header=True, index=False)